Homework 8/app_fifth/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'welcome#index'

  resources :users, only: :show

  namespace :admin do
  	resources :users, except: %i(new create edit)
  end
end

Homework 8/app_fifth/app/models/user.rb
class User < ApplicationRecord

	self.per_page = 5

	mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Homework 8/app_fifth/app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
	before_action :require_admin

	private
	def require_admin
		redirect_to root_path unless current_user.admin?
	end
end

Homework 8/app_fifth/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
	before_action :find_user, except: :index
	def index
		@users = User.paginate(page: params[:page])
	end
	def show
			
	end
	def update
		@user.update(user_params)
	end
	def destroy
		@user.destroy
	end

	private

	def user_params
		params.require(:user).permit(:admin)
	end
	def find_user
		@user = User.find(params[:id])
	end
end

Homework 8/app_fifth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

end

Homework 8/app_fifth/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		
	end
end

Homework 8/app_fifth/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

Homework 8/app_fifth/app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFifth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  	<nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <%= link_to "Admin", admin_users_path, class: "navbar-brand" %>
      </div>
  		<ul class="nav navbar-nav">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Admin Menu", admin_users_path %></li>
				<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  		</ul>
  	</nav>
    <%= yield %>
  </body>
</html>

Homework 8/app_fifth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFifth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  	<nav class="navbar navbar-default">
  		<ul class="nav navbar-nav">
				<% if user_signed_in? %>
  				<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  				<li><%= link_to "Profile", user_path(current_user) %></li>
  				<li><%= link_to "Home", root_path %></li>
					<% if current_user.admin? %>
						<li><%= link_to "Admin Menu", admin_users_path %></li>
					<%end %>
				<% else %>
					<li><%= link_to "Log In", new_user_session_path %></li>
					<li><%= link_to "Register", new_user_registration_path %></li>
				<% end %>
  		</ul>
  	</nav>
    <%= yield %>
  </body>
</html>